version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      -  "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - url-server
  url-server:
    build:
      context: .
    depends_on:
      - mongo
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    command: node index.js
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    volumes:
    - redis-db:/data
volumes:
  mongo-db:
  redis-db:

